package cipher_cracker;

public class Program {
    public static void main(String[] args) {
        EnglishAlphabet e = new EnglishAlphabet();
        CaesarShiftCipher caesarCipher = new CaesarShiftCipher(e);
        CaesarShiftCracker csc = new CaesarShiftCracker(e);

        AffineShiftCracker asc = new AffineShiftCracker(e);
        AffineShiftCipher affineCipher = new AffineShiftCipher(e);

        String plaintext = "ARISTOTLEDEFINEDMATHEMATICSASTHESCIENCEOFQUANTITYANDTHISDEFINITIONPREVAILEDUNTILTHETHCENTURYSTARTINGINTHETHCENTURYWHENTHESTUDYOFMATHEMATICSINCREASEDINRIGORANDBEGANTOADDRESSABSTRACTTOPICSSUCHASGROUPTHEORYANDPROJECTIVEGEOMETRYWHICHHAVENOCLEARCUTRELATIONTOQUANTITYANDMEASUREMENTMATHEMATICIANSANDPHILOSOPHERSBEGANTOPROPOSEAVARIETYOFNEWDEFINITIONSSOMEOFTHESEDEFINITIONSEMPHASIZETHEDEDUCTIVECHARACTEROFMUCHOFMATHEMATICSSOMEEMPHASIZEITSABSTRACTNESSSOMEEMPHASIZECERTAINTOPICSWITHINMATHEMATICSTODAYNOCONSENSUSONTHEDEFINITIONOFMATHEMATICSPREVAILSEVENAMONGPROFESSIONALSTHEREISNOTEVENCONSENSUSONWHETHERMATHEMATICSISANARTORASCIENCEAGREATMANYPROFESSIONALMATHEMATICIANSTAKENOINTERESTINADEFINITIONOFMATHEMATICSORCONSIDERITUNDEFINABLESOMEJUSTSAYMATHEMATICSISWHATMATHEMATICIANSDOTHREELEADINGTYPESOFDEFINITIONOFMATHEMATICSARECALLEDLOGICISTINTUITIONISTANDFORMALISTEACHREFLECTINGADIFFERENTPHILOSOPHICALSCHOOLOFTHOUGHTALLHAVESEVEREPROBLEMSNONEHASWIDESPREADACCEPTANCEANDNORECONCILIATIONSEEMSPOSSIBLEANEARLYDEFINITIONOFMATHEMATICSINTERMSOFLOGICWASBENJAMINPEIRCESTHESCIENCETHATDRAWSNECESSARYCONCLUSIONSINTHEPRINCIPIAMATHEMATICABERTRANDRUSSELLANDALFREDNORTHWHITEHEADADVANCEDTHEPHILOSOPHICALPROGRAMKNOWNASLOGICISMANDATTEMPTEDTOPROVETHATALLMATHEMATICALCONCEPTSSTATEMENTSANDPRINCIPLESCANBEDEFINEDANDPROVENENTIRELYINTERMSOFSYMBOLICLOGICALOGICISTDEFINITIONOFMATHEMATICSISRUSSELLSALLMATHEMATICSISSYMBOLICLOGICINTUITIONISTDEFINITIONSDEVELOPINGFROMTHEPHILOSOPHYOFMATHEMATICIANLEJBROUWERIDENTIFYMATHEMATICSWITHCERTAINMENTALPHENOMENAANEXAMPLEOFANINTUITIONISTDEFINITIONISMATHEMATICSISTHEMENTALACTIVITYWHICHCONSISTSINCARRYINGOUTCONSTRUCTSONEAFTERTHEOTHERAPECULIARITYOFINTUITIONISMISTHATITREJECTSSOMEMATHEMATICALIDEASCONSIDEREDVALIDACCORDINGTOOTHERDEFINITIONSINPARTICULARWHILEOTHERPHILOSOPHIESOFMATHEMATICSALLOWOBJECTSTHATCANBEPROVENTOEXISTEVENTHOUGHTHEYCANNOTBECONSTRUCTEDINTUITIONISMALLOWSONLYMATHEMATICALOBJECTSTHATONECANACTUALLYCONSTRUCTFORMALISTDEFINITIONSIDENTIFYMATHEMATICSWITHITSSYMBOLSANDTHERULESFOROPERATINGONTHEMHASKELLCURRYDEFINEDMATHEMATICSSIMPLYASTHESCIENCEOFFORMALSYSTEMSAFORMALSYSTEMISASETOFSYMBOLSORTOKENSANDSOMERULESTELLINGHOWTHETOKENSMAYBECOMBINEDINTOFORMULASINFORMALSYSTEMSTHEWORDAXIOMHASASPECIALMEANINGDIFFERENTFROMTHEORDINARYMEANINGOFASELFEVIDENTTRUTHINFORMALSYSTEMSANAXIOMISACOMBINATIONOFTOKENSTHATISINCLUDEDINAGIVENFORMALSYSTEMWITHOUTNEEDINGTOBEDERIVEDUSINGTHERULESOFTHESYSTEM";

        try {
            String caesarShiftCiphertext = caesarCipher.encrypt(plaintext, 7);
            String affineShiftCiphertext = affineCipher.encrypt(plaintext, 15, 18);

            CaesarShiftCracker.Result result = csc.guessKey(caesarShiftCiphertext);
            System.out.printf("K: %s%n", result.bestShift);
            System.out.println(caesarCipher.decrypt(caesarShiftCiphertext, result.bestShift));

            AffineShiftCracker.Result affineResult = asc.guessKey(affineShiftCiphertext);
            System.out.printf("A: %s, B: %s%n", affineResult.bestA, affineResult.bestB);
            System.out.println(affineCipher.decrypt(affineShiftCiphertext, affineResult.bestA, affineResult.bestB));

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
}

