package uk.co.cpascoe.caesar_shift_cracker;

public class Program {
    public static void main(String[] args) {
        EnglishAlphabet e = new EnglishAlphabet();
        CaesarShiftCipher caesarCipher = new CaesarShiftCipher(e);
        CaesarShiftCracker csc = new CaesarShiftCracker(e);

        AffineShiftCracker asc = new AffineShiftCracker(e);
        AffineShiftCipher affineCipher = new AffineShiftCipher(e);

        String caesarShiftCiphertext = "HYPZAVASLKLMPULKTHAOLTHAPJZHZAOLZJPLUJLVMXBHUAPAFHUKAOPZKLMPUPAPVUWYLCHPSLKBUAPSAOLAOJLUABYFZAHYAPUNPUAOLAOJLUABYFDOLUAOLZABKFVMTHAOLTHAPJZPUJYLHZLKPUYPNVYHUKILNHUAVHKKYLZZHIZAYHJAAVWPJZZBJOHZNYVBWAOLVYFHUKWYVQLJAPCLNLVTLAYFDOPJOOHCLUVJSLHYJBAYLSHAPVUAVXBHUAPAFHUKTLHZBYLTLUATHAOLTHAPJPHUZHUKWOPSVZVWOLYZILNHUAVWYVWVZLHCHYPLAFVMULDKLMPUPAPVUZZVTLVMAOLZLKLMPUPAPVUZLTWOHZPGLAOLKLKBJAPCLJOHYHJALYVMTBJOVMTHAOLTHAPJZZVTLLTWOHZPGLPAZHIZAYHJAULZZZVTLLTWOHZPGLJLYAHPUAVWPJZDPAOPUTHAOLTHAPJZAVKHFUVJVUZLUZBZVUAOLKLMPUPAPVUVMTHAOLTHAPJZWYLCHPSZLCLUHTVUNWYVMLZZPVUHSZAOLYLPZUVALCLUJVUZLUZBZVUDOLAOLYTHAOLTHAPJZPZHUHYAVYHZJPLUJLHNYLHATHUFWYVMLZZPVUHSTHAOLTHAPJPHUZAHRLUVPUALYLZAPUHKLMPUPAPVUVMTHAOLTHAPJZVYJVUZPKLYPABUKLMPUHISLZVTLQBZAZHFTHAOLTHAPJZPZDOHATHAOLTHAPJPHUZKVAOYLLSLHKPUNAFWLZVMKLMPUPAPVUVMTHAOLTHAPJZHYLJHSSLKSVNPJPZAPUABPAPVUPZAHUKMVYTHSPZALHJOYLMSLJAPUNHKPMMLYLUAWOPSVZVWOPJHSZJOVVSVMAOVBNOAHSSOHCLZLCLYLWYVISLTZUVULOHZDPKLZWYLHKHJJLWAHUJLHUKUVYLJVUJPSPHAPVUZLLTZWVZZPISLHULHYSFKLMPUPAPVUVMTHAOLTHAPJZPUALYTZVMSVNPJDHZILUQHTPUWLPYJLZAOLZJPLUJLAOHAKYHDZULJLZZHYFJVUJSBZPVUZPUAOLWYPUJPWPHTHAOLTHAPJHILYAYHUKYBZZLSSHUKHSMYLKUVYAODOPALOLHKHKCHUJLKAOLWOPSVZVWOPJHSWYVNYHTRUVDUHZSVNPJPZTHUKHAALTWALKAVWYVCLAOHAHSSTHAOLTHAPJHSJVUJLWAZZAHALTLUAZHUKWYPUJPWSLZJHUILKLMPULKHUKWYVCLULUAPYLSFPUALYTZVMZFTIVSPJSVNPJHSVNPJPZAKLMPUPAPVUVMTHAOLTHAPJZPZYBZZLSSZHSSTHAOLTHAPJZPZZFTIVSPJSVNPJPUABPAPVUPZAKLMPUPAPVUZKLCLSVWPUNMYVTAOLWOPSVZVWOFVMTHAOLTHAPJPHUSLQIYVBDLYPKLUAPMFTHAOLTHAPJZDPAOJLYAHPUTLUAHSWOLUVTLUHHULEHTWSLVMHUPUABPAPVUPZAKLMPUPAPVUPZTHAOLTHAPJZPZAOLTLUAHSHJAPCPAFDOPJOJVUZPZAZPUJHYYFPUNVBAJVUZAYBJAZVULHMALYAOLVAOLYHWLJBSPHYPAFVMPUABPAPVUPZTPZAOHAPAYLQLJAZZVTLTHAOLTHAPJHSPKLHZJVUZPKLYLKCHSPKHJJVYKPUNAVVAOLYKLMPUPAPVUZPUWHYAPJBSHYDOPSLVAOLYWOPSVZVWOPLZVMTHAOLTHAPJZHSSVDVIQLJAZAOHAJHUILWYVCLUAVLEPZALCLUAOVBNOAOLFJHUUVAILJVUZAYBJALKPUABPAPVUPZTHSSVDZVUSFTHAOLTHAPJHSVIQLJAZAOHAVULJHUHJABHSSFJVUZAYBJAMVYTHSPZAKLMPUPAPVUZPKLUAPMFTHAOLTHAPJZDPAOPAZZFTIVSZHUKAOLYBSLZMVYVWLYHAPUNVUAOLTOHZRLSSJBYYFKLMPULKTHAOLTHAPJZZPTWSFHZAOLZJPLUJLVMMVYTHSZFZALTZHMVYTHSZFZALTPZHZLAVMZFTIVSZVYAVRLUZHUKZVTLYBSLZALSSPUNOVDAOLAVRLUZTHFILJVTIPULKPUAVMVYTBSHZPUMVYTHSZFZALTZAOLDVYKHEPVTOHZHZWLJPHSTLHUPUNKPMMLYLUAMYVTAOLVYKPUHYFTLHUPUNVMHZLSMLCPKLUAAYBAOPUMVYTHSZFZALTZHUHEPVTPZHJVTIPUHAPVUVMAVRLUZAOHAPZPUJSBKLKPUHNPCLUMVYTHSZFZALTDPAOVBAULLKPUNAVILKLYPCLKBZPUNAOLYBSLZVMAOLZFZALT";

        String affineShiftCiphertext = "";

        try {

            CaesarShiftCracker.Result result = csc.guessKey(caesarShiftCiphertext);
            String plaintext = caesarCipher.decrypt(caesarShiftCiphertext, result.bestShift);

            affineShiftCiphertext = affineCipher.encrypt(plaintext, 7, 15);

            System.out.println(caesarCipher.decrypt(caesarShiftCiphertext, result.bestShift));

            AffineShiftCracker.Result affineResult = asc.guessKey(affineShiftCiphertext);
            System.out.printf("A: %s, B: %s%n", affineResult.bestA, affineResult.bestB);
            System.out.println(affineCipher.decrypt(affineShiftCiphertext, affineResult.bestA, affineResult.bestB));

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
}

